In [3]:
#Ans1:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'list'>
Data type of array_list: <U1


In [5]:
#Ans2:
print("Data type of each element in the list_:")
for element in list_:
    print(f"Element: {element}, Type: {type(element)}")
print("\nData type of each element in the array_list:")
for element in array_list:
    print(f"Element: {element}, Type: {type(element)}")

Data type of each element in the list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data type of each element in the array_list:
Element: 1, Type: <class 'numpy.str_'>
Element: 2, Type: <class 'numpy.str_'>
Element: 3, Type: <class 'numpy.str_'>
Element: 4, Type: <class 'numpy.str_'>
Element: 5, Type: <class 'numpy.str_'>


In [7]:
#Ans3:
array_list = np.array(object=list_, dtype=int)
print("Data type of each element in the list_:")
for element in list_:
    print(f"Element: {element}, Type: {type(element)}")
print("\nData type of each element in the array_list:")
for element in array_list:
    print(f"Element: {element}, Type: {type(element)}")
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("\nData type of each element in the num_array:")
for row in num_array:
    for element in row:
        print(f"Element: {element}, Type: {type(element)}")

Data type of each element in the list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data type of each element in the array_list:
Element: 1, Type: <class 'numpy.int32'>
Element: 2, Type: <class 'numpy.int32'>
Element: 3, Type: <class 'numpy.int32'>
Element: 4, Type: <class 'numpy.int32'>
Element: 5, Type: <class 'numpy.int32'>

Data type of each element in the num_array:
Element: 1, Type: <class 'numpy.int32'>
Element: 2, Type: <class 'numpy.int32'>
Element: 3, Type: <class 'numpy.int32'>
Element: 4, Type: <class 'numpy.int32'>
Element: 5, Type: <class 'numpy.int32'>
Element: 6, Type: <class 'numpy.int32'>


In [17]:
#Ans4:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print('shape-',num_array.shape,'and size-',num_array.size)

shape- (2, 3) and size- 6


In [23]:
#Ans5:
zero_matrix = np.zeros((3, 3))
print("3x3 matrix of zeros:\n",zero_matrix)

3x3 matrix of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
#Ans6:
identity_matrix = np.eye(5)
print("5x5 identity matrix:")
print(identity_matrix)

5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
